/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formamacli;

import javax.swing.JOptionPane;

/**
 *
 * @author Devgoril
 */
public class NewJFrame extends javax.swing.JFrame {

    double bir,iki,sonuc;
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
            setSize(220,245);
            setLocation(300,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        birincisayi1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        islem = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        birincisayi = new javax.swing.JTextField();
        ikincisayi = new javax.swing.JTextField();
        toplama = new javax.swing.JButton();
        cikarma = new javax.swing.JButton();
        carpma = new javax.swing.JButton();
        bolme = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/formamacli/indir.jpg"))); // NOI18N
        jLabel1.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        islem.setEditable(false);
        islem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                islemActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setText("SONUC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(islem, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(islem, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 170, 190, 20);

        birincisayi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                birincisayiActionPerformed(evt);
            }
        });
        getContentPane().add(birincisayi);
        birincisayi.setBounds(10, 60, 185, 27);
        getContentPane().add(ikincisayi);
        ikincisayi.setBounds(10, 100, 185, 27);

        toplama.setText("+");
        toplama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toplamaActionPerformed(evt);
            }
        });
        getContentPane().add(toplama);
        toplama.setBounds(10, 140, 41, 25);

        cikarma.setText("-");
        cikarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikarmaActionPerformed(evt);
            }
        });
        getContentPane().add(cikarma);
        cikarma.setBounds(60, 140, 42, 25);

        carpma.setText("x");
        carpma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carpmaActionPerformed(evt);
            }
        });
        getContentPane().add(carpma);
        carpma.setBounds(110, 140, 44, 25);

        bolme.setText("/");
        bolme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolmeActionPerformed(evt);
            }
        });
        getContentPane().add(bolme);
        bolme.setBounds(160, 140, 37, 25);

        jTextField2.setEditable(false);
        jTextField2.setText("         HESAP MAKİNESİ V1.1");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(-10, 10, 220, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Devgoril\\Desktop\\indir.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setMaximumSize(new java.awt.Dimension(205, 200));
        jLabel2.setMinimumSize(new java.awt.Dimension(205, 200));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 50, 205, 200);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Devgoril\\Desktop\\bilim-insanlarina-gore-gunes-tembellesti,ZpB8Fz5qCUKVzODoQbodmA.jpg")); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-260, -30, 500, 100);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void toplamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toplamaActionPerformed
         
        
        bir = (Double.parseDouble(String.valueOf(birincisayi.getText())));
        iki = (Double.parseDouble(String.valueOf(ikincisayi.getText())));
        sonuc = bir+iki;
        
       islem.setText(String.valueOf(sonuc));
        
    }//GEN-LAST:event_toplamaActionPerformed

    private void cikarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikarmaActionPerformed
        bir = (Double.parseDouble(String.valueOf(birincisayi.getText())));
        iki = (Double.parseDouble(String.valueOf(ikincisayi.getText())));
        
        if(bir<iki) {
            JOptionPane.showMessageDialog(null, "Kucuk Sayidan Buyuk Sayi Cikarmiyoruz..","HATA VAR",JOptionPane.ERROR_MESSAGE);
        }
        else {
                sonuc = bir-iki;
         }
        
       islem.setText(String.valueOf(sonuc));
    }//GEN-LAST:event_cikarmaActionPerformed

    private void carpmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carpmaActionPerformed
          bir = (Double.parseDouble(String.valueOf(birincisayi.getText())));
          iki = (Double.parseDouble(String.valueOf(ikincisayi.getText())));
          sonuc = bir*iki;
        
          islem.setText(String.valueOf(sonuc));        // TODO add your handling code here:
    }//GEN-LAST:event_carpmaActionPerformed

    private void bolmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolmeActionPerformed
        bir = (Double.parseDouble(String.valueOf(birincisayi.getText())));
        iki = (Double.parseDouble(String.valueOf(ikincisayi.getText())));
        sonuc = bir/iki;
        
       islem.setText(String.valueOf(sonuc));        // TODO add your handling code here:
    }//GEN-LAST:event_bolmeActionPerformed

    private void islemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_islemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_islemActionPerformed

    private void birincisayiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_birincisayiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_birincisayiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birincisayi;
    private javax.swing.JTextField birincisayi1;
    private javax.swing.JButton bolme;
    private javax.swing.JButton carpma;
    private javax.swing.JButton cikarma;
    private javax.swing.JTextField ikincisayi;
    private javax.swing.JTextField islem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton toplama;
    // End of variables declaration//GEN-END:variables
}
